#!/usr/bin/env bash
# A bash script that installs nginx on an ubuntu machine.
# This scripts also configures the default webpage served to be "301 Moved Permanently!"
# When request url matches /redirect_me, it redirects to my youtube channel.

apt-get update
sudo apt-get -y install nginx
echo "301 Moved Permanently" |
    sudo tee /usr/share/nginx/html/index.html
sudo sed -i "/# Only for*/i\\
     location /redirect_me {\n\
     rewrite \^(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4\
 permanent;\n}\n" /etc/nginx/sites-available/default
sudo service nginx restart
