#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.

# Update package repositories
sudo apt-get update

# Install nginx
sudo apt-get install nginx -y

# Configure the default page to return "301 Moved Permanently"
echo "301 Moved Permanently" | sudo tee /var/www/html/default

# Configure redirection for /redirect_me
sudo bash -c 'cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;

    index index.html index.htm;

    server_name _;

    location / {
        try_files $uri $uri/ =301;
    }

    location = /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF'

# Restart nginx service
sudo service nginx restart
