#!/usr/bin/env bash
#Bash script to fix container so that Nginx is running as the nginx user.
#nginx must be listening on all active IPs on port 8080.

pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
