#!/usr/bin/env bash
#Bash script that configures the container to fit nginx to nginx
#A shorther version of 1-run_nginx_as_nginx file above.
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
